import api from "./index.js";

export const configurar = api.configurar;
export const config = api.config;
export const obterConfig = api.obterConfig;
export const getConfig = api.getConfig;
export const messages = api.messages;

export const encontrar = api.encontrar;
export const find = api.find;
export const encontrarTodos = api.encontrarTodos;
export const findAll = api.findAll;
export const comparar = api.comparar;
export const compare = api.compare;
export const centro = api.centro;
export const center = api.center;
export const lembrar = api.lembrar;
export const remember = api.remember;
export const lembrado = api.lembrado;
export const remembered = api.remembered;
export const recall = api.recall;
export const esquecer = api.esquecer;
export const forget = api.forget;
export const listarLembrados = api.listarLembrados;
export const listRemembered = api.listRemembered;

export const mover = api.mover;
export const move = api.move;
export const moverSuave = api.moverSuave;
export const moveSmooth = api.moveSmooth;
export const clicar = api.clicar;
export const click = api.click;
export const duploClicar = api.duploClicar;
export const doubleClick = api.doubleClick;
export const cliqueDireito = api.cliqueDireito;
export const rightClick = api.rightClick;
export const pressionar = api.pressionar;
export const press = api.press;
export const soltar = api.soltar;
export const release = api.release;
export const scrollar = api.scrollar;
export const scroll = api.scroll;
export const scrollUntil = api.scrollUntil;
export const arrastar = api.arrastar;
export const drag = api.drag;
export const aguardar = api.aguardar;
export const waitFor = api.waitFor;
export const escrever = api.escrever;
export const type = api.type;
export const digitar = api.digitar;
export const write = api.write;
export const mic = api.mic;
export const screenshot = api.screenshot;
export const print = api.print;
export const capturar = api.capturar;
export const capture = api.capture;

export default api;
